import './globals.css'

import { Poppins, Roboto } from "next/font/google"

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

const poppins = Poppins({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${roboto.className}`}>{children}</body>
    </html>
  )
}
